### PR TITLE
Add Count field in people-density analytic

### PR DESCRIPTION
**Pull request by gregoriusjimmy**
## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

There is no count field in people-density analytic

## What is the new behavior?

AnalyticResult now will add a count field if it is a people-density analytic

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

image

### CODE REVIEW

**Comment by sonadztux** [comment]
@gregoriusjimmy count-nya ga ditaruh di bawah result thumbnail-nya aja, Jim?

**Comment by gregoriusjimmy** [comment]
> @gregoriusjimmy count-nya ga ditaruh di bawah result thumbnail-nya aja, Jim?

countnya jadi less important nanti nan

**Comment by rizkybaihaqy** [comment]
> countnya jadi less important nanti nan

kalo dapet dua kolom bisa ga jim?

**Comment by williammfu** [comment]
Dua kolom kaya gimana maksudnya ky? Btw sekarang kalau layout nya mau di-_customize_ lagi buat `count` kayanya butuh effort ya

**Comment by gregoriusjimmy** [comment]
> > Dua kolom kaya gimana maksudnya ky? Btw sekarang kalau layout nya mau di-customize lagi buat count kayanya butuh effort ya
> 
> image jadi sepanjang itu fu biar seimbang.

Gapapa ki kyak gitu dlu aja udh bagus mnrut gw

**Review by lazuardyk — APPROVED** [review]

**Review by williammfu — APPROVED** [review]

**Pull request merged**
