### PR TITLE
[Frontend] Implemented AML/PEP Modal

### PR DESCRIPTION
**Pull request by williammfu**
## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

- Sijitu (one of the solution partner) lacks a popup element when clicked

## What is the new behavior?
- A popup for user's email consent is implemented according to wireframe provided with the proper completeness value

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md)

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gregoriusjimmy — APPROVED** [review]
LGTM!

**Review by sonadztux — APPROVED** [review]

**Comment by sonadztux** [comment]
@williammfu cuman minta tolong nanti kalo mau ngetes/deploy musti ada env yang di-update ya

**Comment by williammfu** [comment]
Oh iya, thanks remindernya nan, buat .env nya perlu diubah di file mana aja ya? (selain .env.example di frontend)
Soalnya gue liat script deployment nya ada env sendiri juga?

**Comment by sonadztux** [comment]
> Oh iya, thanks remindernya nan, buat .env nya perlu diubah di file mana aja ya? (selain .env.example di frontend) Soalnya gue liat script deployment nya ada env sendiri juga?

- .env.example yang di root project,
- docker-compose.yaml, 
- /deployment/frontend.yaml

cmiiw cc @lazuardyk @asyafalni

**Comment by sonadztux** [comment]
@williammfu Gue coba di local, harusnya kalo belum ada session (belum ngisi request demo form) dia bakal muncul form request demo dulu

**Comment by williammfu** [comment]
> @williammfu Gue coba di local, harusnya kalo belum ada session (belum ngisi request demo form) dia bakal muncul form request demo dulu

Oh perlu login juga ya? Noted kalo gitu ditambah dulu ya

**Comment by gregoriusjimmy** [comment]
> @williammfu Gue coba di local, harusnya kalo belum ada session (belum ngisi request demo form) dia bakal muncul form request demo dulu

oh iya gw jg miss ini

**Comment by williammfu** [comment]
## Update
Request form modal added, re-review please. Thanks!

**Review by sonadztux — APPROVED** [review]
Udah sesuai requirement. Mantap. Keep it up!

**Comment by sonadztux** [comment]
@williammfu sikat merge Fu

**Pull request merged**
