### PR TITLE
Sticky Navbar, Fix Carousel still slide when dot clicked

### PR DESCRIPTION
**Pull request by gregoriusjimmy**
## Type of changes

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

- Navbar being sticky only in tablet and mobile devices
- Carousel still slide 1 more time when dot is clicked

## What is the new behavior?

- Make Navbar sticky on all devices
- Change background color Hero section to use linear gradient
- Navbar will use linear-gradient color only in home page
- Fix Carousel still slide 1 more time when dot is clicked by adding componentDidUnmount
## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

stickynavbar1
stickynavbar2

### CODE REVIEW

**Review by sonadztux — APPROVED** [review]
😍

**Review by williammfu — APPROVED** [review]

**Review by rizkybaihaqy — COMMENTED** [review]
jim, menurut gw alt dari image yg lu buat kurang meaningful. gw ada saran ni buat diganti jadi
- cover-image -> hero-image
- solution-01 -> solution-intersection-image
- logogram ->visual of a quarter circle
- products-91 -> product-intersection-image

**Comment by gregoriusjimmy** [comment]
> jim, menurut gw alt dari image yg lu buat kurang meaningful. gw ada saran ni buat diganti jadi
> 
> * cover-image -> hero-image
> * solution-01 -> solution-intersection-image
> * logogram ->visual of a quarter circle
> * products-91 -> product-intersection-image

widihh bagus nih otw ganti

**Comment by gregoriusjimmy** [comment]
> > jim, menurut gw alt dari image yg lu buat kurang meaningful. gw ada saran ni buat diganti jadi
> > 
> > * cover-image -> hero-image
> > * solution-01 -> solution-intersection-image
> > * logogram ->visual of a quarter circle
> > * products-91 -> product-intersection-image
> 
> widihh bagus nih otw ganti

done in https://github.com/nodefluxio/weber/pull/153/commits/34a621eee795cc8a29603e67dd78d40f8839de90

**Review by rizkybaihaqy — APPROVED** [review]

**Pull request merged**
