### PR TITLE
[Frontend] Improvements on OCR innovations result display

### PR DESCRIPTION
**Pull request by williammfu**
## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?
The OCR Innovation result display has the following issues
- Scrollbar component is not visible
- Vanilla JSON string, not colorized
- No button to instantly copy JSON string
- On the text format result, there is still unnecessary info from the AI response

## What is the new behavior?

The OCR Innovation result display now has the following format
- Visible scrollbar
- JSON string is colorized (edited _base dan _variables scss files for the mono font family)
- A button is provided to copy the JSON string to the clipboard (appear on hover)
- On the text format, all unnecessary field from the AI response are removed

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md)

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by sonadztux — APPROVED** [review]

**Comment by williammfu** [comment]
Updates:
- Remove "Additional Info" header from the text format
- Changed the "Copy to clipboard" button to a simple icon button

**Review by gregoriusjimmy — COMMENTED** [review]
keren banget, tinggal changelognya @williammfu

**Comment by gregoriusjimmy** [comment]
oh iya visible scrollbalnya yg tab Text juga ada kan fu?

**Comment by williammfu** [comment]
> oh iya visible scrollbalnya yg tab Text juga ada kan fu?

yes visible juga

> keren banget, tinggal changelognya @williammfu

yang unreleased skrg udah masuk v0.4.0 ya?

**Review by gregoriusjimmy — APPROVED** [review]

**Comment by gregoriusjimmy** [comment]
> > oh iya visible scrollbalnya yg tab Text juga ada kan fu?
> 
> yes visible juga
> 
> > keren banget, tinggal changelognya @williammfu
> 
> yang unreleased skrg udah masuk v0.4.0 ya?

iyo fu

**Review by sonadztux — APPROVED** [review]

**Pull request merged**
