### PR TITLE
Feat/new face payment get api

### PR DESCRIPTION
**Pull request by rizkybaihaqy**
## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

we call api for checking phone number and then backend decide if the user required to fill out fill form.

## What is the new behavior?

we fetch the get api at main menu and then store the data in state. later we use the state to decide if user enter the correct phone number and if the user passed their shopping limit. if the user has exceed their shopping limit then we show pin input form. as a bonus now we show balance on catalog browsing step. after all this step, we still use the same process as before.

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sonadztux** [comment]
@rizkybaihaqy ada yang gagal build

**Comment by rizkybaihaqy** [comment]
gw gatau nan itu kenapa gagal. banyak banget error dan warningnnya. agak ribet kalo emang harus di fix semua di MR ini

**Comment by valdmir** [comment]
@rizkybaihaqy flow lu gw ga nangkep dari new behaviour yang lu sampein.
bisa elaborate atau kasi pembatas ga?

**Comment by sonadztux** [comment]
> @rizkybaihaqy flow lu gw ga nangkep dari new behaviour yang lu sampein. bisa elaborate atau kasi pembatas ga?

Bantu jawab. Sebelumnya dari backend ada satu endpoint buat cek apakah suatu session id punta akun face payment aktif atau ga, return responsnya cuman true/false. Sedangkan kita ada kebutuhan cek total belanjaan melebihi limit minimum payment & kecocokan phone number serta data akun.

Nah yang sekarang endpoint yang awalnya cuman buat cek apakah suatu session id punya akun aktif ini diubah response-nya biar sekalian provide data akun, jadi ga perlu endpoint lagi yang buat cek limit, pengecekannya di frontend dari data respons yang didapat

**Comment by lazuardyk** [comment]
@rizkybaihaqy errornya disini ky setelah gw liat log buildnya di github action:
```
./app/api/paymentAPI.ts
5:3  Error: 'CheckLimitResponse' is defined but never used.  @typescript-eslint/no-unused-vars
```

kalo yang warning kan bisa di ignore dulu, kalo error ini gabisa karena jadi gagal build

**Comment by rizkybaihaqy** [comment]
owala disitu, ini gw close dulu deh. ada task lain buat reset balance yang kyknya gabisa dipisah. sekalian sama error nya.

**Pull request closed without merging**
