### PR TITLE
[Beat] Update description on seeds data

### PR DESCRIPTION
**Pull request by bagasteguhimani**
## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Enhancement
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

No services description

## What is the new behavior?

Add Description for Services

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by lazuardyk — APPROVED** [review]

**Comment by lazuardyk** [comment]
Special Instruction jadi dipake gak ya?

**Review by sonadztux — APPROVED** [review]
Lgtm. Cuman minta tolong dikit label PR-nya ditambahin sama update changelog [Unreleased] yang Changes. @bagasteguhimani

**Review by krismp — APPROVED** [review]
Akhirnya ada yg ganti juga ❤️ thx @bagasteguhimani 

lgtm, minus comment nya @sonadztux

**Review by gregoriusjimmy — APPROVED** [review]

**Comment by sonadztux** [comment]
@bagasteguhimani ada conflict

**Comment by sonadztux** [comment]
Makin konflik

**Comment by sonadztux** [comment]
@bagasteguhimani lo nge-resolve tapi kaga jadi nambahin pesan changelog lo dong kalo gitu

**Comment by sonadztux** [comment]
@bagasteguhimani udah gue bantu resolve, kayaknya udah safe to merge.

**Comment by bagasteguhimani** [comment]
Okee tengkyu nan @sonadztux

**Pull request merged**
