### PR TITLE
Fix eslint configuration

### PR DESCRIPTION
**Pull request by williammfu**
## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

ESLint did not cover modules on /app folder

## What is the new behavior?

Add ESLint configuration on `next.config.js` to cover /app folder

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md)

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Please recheck whether the features work properly, thanks

### CODE REVIEW

**Comment by krismp** [comment]
banyak bgt @williammfu wkwkwk

btw ada conflict, tambah ini dong fu https://eslint.org/docs/rules/no-console

**Comment by gregoriusjimmy** [comment]
banyak bgt changesnya ya fu, bakal breaking changes ga ya? @williammfu

**Comment by williammfu** [comment]
> btw ada conflict, tambah ini dong fu https://eslint.org/docs/rules/no-console

wokee noted kak <br/><br/>

> banyak bgt changesnya ya fu, bakal breaking changes ga ya?

setelah diliat" keanya bisa jadi deh 😓

**Comment by gregoriusjimmy** [comment]
> > btw ada conflict, tambah ini dong fu https://eslint.org/docs/rules/no-console
> 
> wokee noted kak
> 
> > banyak bgt changesnya ya fu, bakal breaking changes ga ya?
> 
> setelah diliat" keanya bisa jadi deh 😓

coba fix conflictnya dlu deh fu mau gw coba branchnya, setelah gw review lagi kyaknya aman deh

**Comment by williammfu** [comment]
ohiya kak @krismp `no-console` disallow semua method aja ya ? (including `console.error`)

**Comment by krismp** [comment]
@williammfu iya fu, takut ada `console.log("wkwkwk")`, console error sm warning klo perlu bisa di exclude, configurable kan ya rule nya:

```
/* eslint no-console: ["error", { allow: ["warn", "error"] }] */

console.warn("Log a warn level message.");
console.error("Log an error level message.");
```

**Comment by williammfu** [comment]
wokee buat skrg `console.error` masih allow dulu ya

**Review by gregoriusjimmy — APPROVED** [review]
Nice, thanks @williammfu jadi berguna eslintnya kwwkkw

**Review by krismp — APPROVED** [review]
Lgtm

**Pull request merged**
