### PR TITLE
Modify Homepage, Navbar, Footer, Carousel

### PR DESCRIPTION
**Pull request by gregoriusjimmy**
## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

- CarouselItem can be used only for new innovations
- Navbar is not fixed in smaller devices
- Homepage still have our demo, and awards and recognitions section

## What is the new behavior?

- Make CarouselItem reusable
- Carousel now automatically slide every given delay 
- Carousel have vertical and withButton options
- Make Navbar fixed at the top on smaller devices
- Apply new hero section in Homepage,
- Delete our demo, and awards and recognitions section on Homepage
- Add awards and recognitions, and products in Footer
## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Revamp homepage
screencapture-localhost-3000-2021-11-20-07_04_27
hero
image
image
image

### CODE REVIEW

**Review by sonadztux — APPROVED** [review]
GOKIL! @gregoriusjimmy sekalian update changelog jim

**Review by rizkybaihaqy — APPROVED** [review]

**Comment by gregoriusjimmy** [comment]
> GOKIL! @gregoriusjimmy sekalian update changelog jim

ngisi changelognya kayak gini ga nan? @sonadztux

**Comment by williammfu** [comment]
[Unreleased] nya gaperlu diganti jim

**Review by williammfu — APPROVED** [review]

**Comment by sonadztux** [comment]
> > GOKIL! @gregoriusjimmy sekalian update changelog jim
> 
> ngisi changelognya kayak gini ga nan? @sonadztux [b4671ae](https://github.com/nodefluxio/weber/commit/b4671ae4dea5a5dce9e7743da26ede7a522b9d27)

Nah iya bener kata Fu, masukkin [Unreleased] dulu @gregoriusjimmy

**Comment by gregoriusjimmy** [comment]
> > > GOKIL! @gregoriusjimmy sekalian update changelog jim
> > 
> > 
> > ngisi changelognya kayak gini ga nan? @sonadztux [b4671ae](https://github.com/nodefluxio/weber/commit/b4671ae4dea5a5dce9e7743da26ede7a522b9d27)
> 
> Nah iya bener kata Fu, masukkin [Unreleased] dulu @gregoriusjimmy

owh yg ini berarti masih salah changelognya

**Comment by sonadztux** [comment]
> > 
> > Nah iya bener kata Fu, masukkin [Unreleased] dulu @gregoriusjimmy
> 
> owh yg ini berarti masih salah changelognya
@gregoriusjimmy iya kek punya gue gini https://github.com/nodefluxio/weber/pull/130/commits/429887415b7d77a338e8f7ca623817be1c7fcff0

**Pull request merged**
