### PR TITLE
Update the Dockerfile in backend to work on Windows

### PR DESCRIPTION
**Pull request by lazuardyk**
## Type of changes

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?
When I run on Windows using docker-compose, I got this error:

Screenshot_1909

## What is the new behavior?
Fixed it by using dos2unix to format the bash file.

### CODE REVIEW

**Comment by sonadztux** [comment]
Ini lo run di Windows ga pakai WSL berarti ya? @lazuardyk

**Comment by lazuardyk** [comment]
> Ini lo run di Windows ga pakai WSL berarti ya? @lazuardyk

Runnya di terminal vscode, pake docker yang run dengan WSL 2

**Comment by sonadztux** [comment]
@bagasteguhimani lo pake windows kan ya? Cobain ini dong bisa running ga via docker-compose. Gue dari semalem nyoba (OS: Linux Mint) jadi error, tapi masih belum yakin gara-gara ini atau bukan.

**Comment by bagasteguhimani** [comment]
sorry baru nyobain, di gw work nan @sonadztux

**Review by bagasteguhimani — APPROVED** [review]

**Pull request merged**
