### PR TITLE
[Frontend] Solution Carousel Adjustments

### PR DESCRIPTION
**Pull request by williammfu**
## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Enhancement
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

On the homepage carousel, there's a mix between the business solution card (tailored by Nodeflux) and partner's solutions card

## What is the new behavior?

There's a new carousel provided for solutions by partner

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md)

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by williammfu** [comment]
### Update
Align Solution card to middle (desktop view, mobile view remained the same as usual)

image

**Review by gregoriusjimmy — APPROVED** [review]

**Comment by rizkybaihaqy** [comment]
> When enabled it center slides if the amount of slides less than slidesPerView. Not intended to be used loop mode and grid.rows

https://swiperjs.com/swiper-api#param-centerInsufficientSlides

sorry telat ges, tapi gw nemu cara biar dia center bawaan dari librarynya langsung. kyknya lebih enak pake yang dari librarynya aja deh menurut gw.

**Comment by gregoriusjimmy** [comment]
> > When enabled it center slides if the amount of slides less than slidesPerView. Not intended to be used loop mode and grid.rows
> 
> https://swiperjs.com/swiper-api#param-centerInsufficientSlides
> 
> sorry telat ges, tapi gw nemu cara biar dia center bawaan dari librarynya langsung. kyknya lebih enak pake yang dari librarynya aja deh menurut gw.

boleh ni dicoba dlu @williammfu

**Comment by williammfu** [comment]
Makasihh masukannya ky, udah gue push updatesnya

**Review by rizkybaihaqy — APPROVED** [review]

**Pull request merged**
