### PR TITLE
Update background and Banner images for all innovations

### PR DESCRIPTION
**Pull request by gregoriusjimmy**
## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

- AnalyticsContainer is hardcoded to use analytics assets folder
- Innovations doesn't have banner images
## What is the new behavior?

- AnalyticsContainer now can pass custom banner url as props
- Add innovations banner images
- Add and update innovations background image
## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by gregoriusjimmy** [comment]
@sonadztux @lazuardyk @bagasteguhimani gw ganti seed.go jadi kyak gini problem ga?

**Comment by sonadztux** [comment]
> @sonadztux @lazuardyk @bagasteguhimani gw ganti seed.go jadi kyak gini problem ga?

ocr receipt sama car damage doang yang jpg? Occlusion attribute kaga?

**Comment by lazuardyk** [comment]
> @sonadztux @lazuardyk @bagasteguhimani gw ganti seed.go jadi kyak gini problem ga?

kaga. cuman harus update database yg di production

**Comment by rizkybaihaqy** [comment]
knapa harus ada props custom image url?

**Comment by gregoriusjimmy** [comment]
> knapa harus ada props custom image url?

component AnalyticPage dipake di ocr-receipt sama face occlusion page

**Review by rizkybaihaqy — APPROVED** [review]

**Review by williammfu — APPROVED** [review]
👀🐱

**Pull request merged**
