### PR TITLE
[Beat] Fix seeder to update when the data already exists & update docker entrypoint

### PR DESCRIPTION
**Pull request by lazuardyk**
## Type of changes

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?
Currently updating data is not working with the command ```go run . seed``` especially in services. #152 

## What is the new behavior?
We can use ```go run . seed``` for updating services when we have new or changed services in the seeder.

### CODE REVIEW

**Comment by sonadztux** [comment]
Kok ga work ya di gue. Gue coba pengen update slug-nya OCR receipt tapi malah jadi double dengan id berbeda dan error message-nya malah duplicate key pas mau insert seed face payment. 

Error message:
Screenshot at 2021-11-28 19-20-38

Data OCR Receipt malah jadi double:
Screenshot at 2021-11-28 19-22-19

**Comment by lazuardyk** [comment]
> Kok ga work ya di gue. Gue coba pengen update slug-nya OCR receipt tapi malah jadi double dengan id berbeda dan error message-nya malah duplicate key pas mau insert seed face payment.
> 
> Error message: Screenshot at 2021-11-28 19-20-38
> 
> Data OCR Receipt malah jadi double: Screenshot at 2021-11-28 19-22-19

Oh itu karena gua make get service by slug wkwk, ga kepikiran buat ngerubah slug waktu itu pas gua ngoding.
Udah gua update jadi get by id https://github.com/nodefluxio/weber/pull/157/commits/759fd7bf77762c09c0f5867b60fa3638eff00d6b , bisa di coba lagi ya.

Thanks nan

**Comment by sonadztux** [comment]
> Oh itu karena gua make get service by slug wkwk, ga kepikiran buat ngerubah slug waktu itu pas gua ngoding. Udah gua update jadi get by id [759fd7b](https://github.com/nodefluxio/weber/commit/759fd7bf77762c09c0f5867b60fa3638eff00d6b) , bisa di coba lagi ya.
> 
> Thanks nan

Gue coba udah works buat update data sama nambah data seed baru, cuman ini id nya jadi di-hardcode gitu ya. Emang gapapa?

**Comment by lazuardyk** [comment]
> > Oh itu karena gua make get service by slug wkwk, ga kepikiran buat ngerubah slug waktu itu pas gua ngoding. Udah gua update jadi get by id [759fd7b](https://github.com/nodefluxio/weber/commit/759fd7bf77762c09c0f5867b60fa3638eff00d6b) , bisa di coba lagi ya.
> > Thanks nan
> 
> Gue coba udah works buat update data sama nambah data seed baru, cuman ini id nya jadi di-hardcode gitu ya. Emang gapapa?

Iya nan, mau gamau harus make sih karena untuk update yg udah ada di db kita perlu query dari id nya. Untuk cons nya menurut gua ngga ada karena ini data services juga kan yang kita definisiin sendiri dan ga nambah sendiri gitu kyk yg lain. Wdyt?

**Comment by sonadztux** [comment]
@lazuardyk gue set labelnya jadi `on hold` dulu selagi lo masih develop admin dashboard #48 sebagai alternative solution buat ini

**Pull request closed without merging**
