### PR TITLE
Edit minimal input to 5 char for job title, company name in request demo form, fix sticky navbar

### PR DESCRIPTION
**Pull request by gregoriusjimmy**
## Type of changes

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

- Currently, minimum input length for field title and company name is 1 char
- Sticky navbar not on the top of page because of margin
## What is the new behavior?

- Make minimum input length for field title and company name to 5 char
- Fix sticky navbar in request demo form by changing margin to padding
## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by sonadztux — APPROVED** [review]

**Comment by sonadztux** [comment]
Eh @lazuardyk buat ini backend-nya perlu diupdate juga ga, sih?

**Comment by sonadztux** [comment]
Btw @gregoriusjimmy ini ga sekalian nambahin checkbox buat accept terms of service ya?

**Comment by gregoriusjimmy** [comment]
> Btw @gregoriusjimmy ini ga sekalian nambahin checkbox buat accept terms of service ya?

di jual terpisah ya mas

**Review by williammfu — APPROVED** [review]

**Comment by lazuardyk** [comment]
> Eh @lazuardyk buat ini backend-nya perlu diupdate juga ga, sih?

Iya perlu dirubah si min maxnya juga

**Pull request merged**
