### PR TITLE
change some assets

### PR DESCRIPTION
**Pull request by asyafalni**
## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Enhancement
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): 

## What is the new behavior?
Asset changes, sama size adjustment on HomePage

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/weber/blob/main/CHANGELOG.md

## Security Pentester API Checklist
- [ ] IDOR
- [ ] Malicious Script Injection
- [ ] SQL Injection

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by asyafalni — COMMENTED** [review]
review gan @gregoriusjimmy @rizkybaihaqy @williammfu

**Review by williammfu — APPROVED** [review]
All good, kak. Tinggal update Changelog aja (kalo butuh).

**Comment by asyafalni** [comment]
> All good, kak. Tinggal update Changelog aja (kalo butuh).

ga usah gpp, changesnya ga crucial

**Comment by rizkybaihaqy** [comment]
image
ini maskernya memang putih atau lupa dibuat transparant ya?

**Comment by asyafalni** [comment]
> image ini maskernya memang putih atau lupa dibuat transparant ya?

enag dari icon yang dibikin anak intern gitu @rizkybaihaqy , biar ga nyaru ama background, dan keliatan pake maskernya

**Review by gregoriusjimmy — APPROVED** [review]

**Pull request merged**
